'use strict';
// ============================================================
// CANOE ARENA — Netlify build step.
// Injects the CANOE_SERVER env var (game server host) into the
// static bundle so the client knows where to find the WebSocket.
// Usage: node scripts/build.js
// ============================================================
const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, '..', 'public', 'js', 'server-config.js');
const host = (process.env.CANOE_SERVER || '').trim();

const content = `// Auto-generated by scripts/build.js (Netlify build). Do not edit by hand.
// Set CANOE_SERVER to the deployed game-server host (e.g. "canoe-arena.onrender.com")
// and it will be injected here. Empty = same-origin (localhost / LAN play).
window.CANOE_SERVER = ${JSON.stringify(host)};
`;

fs.writeFileSync(target, content);
console.log(`[build] server-config.js -> CANOE_SERVER=${host || '(same-origin)'}`);
